version: 3.8

services:
  registry:
    container_name: infra-services-core_registry
    hostname: registry
    image: docker.io/registry:2
    networks:
    - infra-services-core
    ports:
    - 5000:5000/tcp
    restart: always
    volumes:
    - type: volume
      source: registry-data
      target: /var/lib/registry

networks:
  infra-services-core:

volumes:
  registry-data:
